# Generated by Django 3.1.1 on 2020-09-19 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('written_username', models.CharField(max_length=120, verbose_name='Вас зовут')),
                ('written_phone', models.CharField(max_length=120, verbose_name='Ваш телефон')),
                ('written_cover_letter', models.TextField(verbose_name='Сопроводительное письмо')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название компании')),
                ('location', models.CharField(max_length=120, verbose_name='География')),
                ('logo', models.ImageField(default='default.gif', height_field='height_field', upload_to='company_images', verbose_name='Логотип', width_field='width_field')),
                ('height_field', models.PositiveIntegerField(default=0)),
                ('width_field', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(verbose_name='Информация о&nbsp;компании')),
                ('employee_count', models.CharField(max_length=80, verbose_name='Количество человек в компании')),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Имя')),
                ('surname', models.CharField(max_length=120, verbose_name='Фамилия')),
                ('status', models.CharField(choices=[('NIS', 'Не ищу работу'), ('C', 'Рассматриваю предложения'), ('IS', 'Ищу работу')], max_length=80, verbose_name='Готовность к работе')),
                ('salary', models.PositiveIntegerField(verbose_name='Ожидаемое вознаграждение')),
                ('grade', models.CharField(choices=[('intern', 'Стажер'), ('junior', 'Джуниор'), ('middle', 'Миддл'), ('senior', 'Синьор'), ('lead', 'Лид')], max_length=80, verbose_name='Квалификация')),
                ('education', models.TextField(verbose_name='Образование')),
                ('experience', models.TextField(verbose_name='Опыт работы')),
                ('portfolio', models.CharField(max_length=120, verbose_name='Ссылка на портфолио')),
            ],
        ),
    ]
