# Generated by Django 3.1.1 on 2020-09-14 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_home', '0002_auto_20200914_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='employee_count',
            field=models.CharField(max_length=80),
        ),
    ]
