# Generated by Django 3.1.1 on 2020-09-16 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_home', '0004_auto_20200915_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(verbose_name='Информация о&nbsp;компании'),
        ),
        migrations.AlterField(
            model_name='company',
            name='employee_count',
            field=models.CharField(max_length=80, verbose_name='Количество человек в компании'),
        ),
        migrations.AlterField(
            model_name='company',
            name='location',
            field=models.CharField(max_length=120, verbose_name='География'),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(height_field='height_field', upload_to='company_images', verbose_name='Логотип', width_field='width_field'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Название компании'),
        ),
    ]
