# Generated by Django 3.1.1 on 2020-09-16 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_home', '0005_auto_20200916_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(default='https://place-hold.it/120x40', height_field='height_field', upload_to='company_images', verbose_name='Логотип', width_field='width_field'),
        ),
    ]
