# Generated by Django 3.1.1 on 2020-09-18 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_vacancy', '0003_auto_20200918_1613'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_home', '0007_auto_20200916_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Имя')),
                ('surname', models.CharField(max_length=120, verbose_name='Фамилия')),
                ('status', models.CharField(choices=[('NIS', 'Не ищу работу'), ('C', 'Рассматриваю предложения'), ('IS', 'Ищу работу')], max_length=80, verbose_name='Готовность к работе')),
                ('salary', models.PositiveIntegerField(verbose_name='Вознаграждение')),
                ('grade', models.CharField(choices=[('intern', 'Стажер'), ('junior', 'Джуниор'), ('middle', 'Миддл'), ('senior', 'Синьор'), ('lead', 'Лид')], max_length=80, verbose_name='Квалификация')),
                ('education', models.TextField(verbose_name='Образование')),
                ('experience', models.TextField(verbose_name='Опыт работы')),
                ('portfolio', models.CharField(max_length=120, verbose_name='Портфолио')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='app_vacancy.specialty', verbose_name='Специальность')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
