# Generated by Django 3.1.1 on 2020-10-07 17:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80, unique=True)),
                ('title', models.CharField(max_length=120)),
                ('picture', models.ImageField(height_field='height_field', upload_to='speciality_images', width_field='width_field')),
                ('height_field', models.PositiveIntegerField(default=0)),
                ('width_field', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Название вакансии')),
                ('skills', models.CharField(max_length=120, verbose_name='Требуемые навыки')),
                ('description', models.TextField(verbose_name='Описание вакансии')),
                ('salary_min', models.PositiveIntegerField(verbose_name='Зарплата от')),
                ('salary_max', models.PositiveIntegerField(verbose_name='Зарплата до')),
                ('published_at', models.DateField(default=datetime.date.today)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='app_company.company')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='app_vacancy.specialty', verbose_name='Специальность')),
            ],
        ),
    ]
