# Generated by Django 3.1.1 on 2020-09-10 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_vacancy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialty',
            name='code',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
