# Generated by Django 3.1.1 on 2020-10-07 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название компании')),
                ('location', models.CharField(max_length=120, verbose_name='География')),
                ('logo', models.ImageField(default='default.gif', height_field='height_field', upload_to='company_images', verbose_name='Логотип', width_field='width_field')),
                ('height_field', models.PositiveIntegerField(default=0)),
                ('width_field', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(verbose_name='Информация о&nbsp;компании')),
                ('employee_count', models.CharField(max_length=80, verbose_name='Количество человек в компании')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
